name: 'bomber-action'
description: 'Action using DevOps Kung Fu Bomber'
author: Drahtzieher
inputs:
  bomber_version:
    description: enter the release you want to use
    required: false
    default: v0.4.8
  sbom-file:
    description: 'the sbom file to scan '
    required: true
    default: sbom.json
  data-provider:
    description: 'snyk or ossindex or ovs'
    required: false
    default: "ovs"
  output_format:
    description: 'Options are stdout, json,html'
    required: false
    default: "stdout"
  output-file:
    description: 'filename for output file. if empty or output not set to html or json, no file will be generated.'
    required: false
    default: bomber_output
  ignore-file:
    description: name of the file containing CVEs to ignore
    required: false
runs:
  using: docker
  image: Dockerfile

